### PR TITLE
Add AUTHORS file

### PR DESCRIPTION
**Pull request by treyhunner**
@BrianHicks, @bkg, @xuhdev feel free to provide me with an email address or website that you would like me to link to

### CODE REVIEW

**Comment by BrianHicks** [comment]
Let's go with brian@brianthicks.com for me

**Comment by xuhdev** [comment]
hong AT topbug DOT net, http://www.topbug.net

**Comment by bkg** [comment]
I'm at <bkgaley at gmail dot com>, thanks!

**Comment by treyhunner** [comment]
Updated.  I took your obfuscated suggestions literally.  Feel free to comment/PR to update if desired.

Thanks all!

**Pull request merged**
