### PR TITLE
adds arguments parsing

### PR DESCRIPTION
**Pull request by farfanoide**
adds main loop for parsing arguments; current supported arguments are:
-h -- Show help dialog.
-l -- List all available session files.

Implemented whith a while loop and parsed with the sh/bash builtin
'getopts' which gives the possibility of chainning arguments together
like so:
    `tmuxstart -hl`
or:
    `tmuxstart -h -l`

### CODE REVIEW

**Comment by treyhunner** [comment]
Instead of

```
tmuxstart options:
==================
tmuxstart tmux-session   -- Start/Attach session
tmuxstart -h             -- Print help menu
tmuxstart -l             -- List all available session files
```

what do you think of something like

```
Usage: tmuxstart [OPTIONS] SESSION

Launch reusable configurations for named tmux sessions.

Options:
  -h     Print help menu
  -l     List all available session files
```

**Comment by treyhunner** [comment]
Is there no way to also allow `--help`?

Currently the output for `tmuxstart --help` is strange.  It prints the usage statement twice with an Invalid option warning in between.

**Comment by farfanoide** [comment]
here's the deal with flags: they suck!
basically you gotta chose between long readable flags and parsing it's arguments by hand, or have short, one letter flags with automatic parsing.
options here are as they follow:
short letter flags can be achieved (as it's done here) by using the unix builting getopts (http://en.wikipedia.org/wiki/Getopts). 
pros: 
- flags can be passed together, ie: -a -e -z = -aez
- rather simple logic for parsing them
- flags can have a space between them and the arguments passed or not, ie: -uroot = -u root
- arguments parsing is done by getopts itself
- portability: getopts WILL be available

cons:
- cant use long, pretty flags, ie: --help

note on getotps: some level of support for long flags could be achieved as stated here(http://stackoverflow.com/a/7680682/2287459)

long flags can be done in various ways, most notably with the getopt program (not built in), however there's a major downside to this approach and that is: getopt has 2 very different implementations (GNU | BSD) which differ greatly.
they could also be done by hand as stated here (http://stackoverflow.com/a/7069755/2287459)
pros:
- more readable flags
- one could have aliases to flags, ie: -l = --list = list  

cons:
- parsing of arguments is done by hand with regular expressions, which could end in having some rather strange, unreadable regex

i chose the getopts approach beacause of portability and simplicity

**Comment by treyhunner** [comment]
It would be nice to eventually support long flags, but short flags are better than no flags so I'm fine with the current implementation for now.

**Comment by farfanoide** [comment]
i implemented a very basic version of how we could parse both short and long flags in my personal branch https://github.com/farfanoide/tmuxstart/commit/5c6ba0788e9907e2cc3157f70645ae4b58ec6735

**Comment by treyhunner** [comment]
@farfanoide want to start a new pull request to make the flags even better?  I'll try to take a look this weekend.

**Pull request merged**
